
(SELECT CITY, LENGTH(CITY) AS NAME_LENGTH 
 FROM STATION 
 ORDER BY NAME_LENGTH ASC, CITY ASC 
 LIMIT 1)
UNION 
(SELECT CITY, LENGTH(CITY) AS NAME_LENGTH
FROM STATION
ORDER BY NAME_LENGTH DESC, CITY DESC
LIMIT 1)
